# Generated by Django 3.2.4 on 2022-03-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productflower',
            name='product',
            field=models.ForeignKey(limit_choices_to={'status': 'На продаже'}, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
