# Generated by Django 3.2.4 on 2022-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220312_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productflower',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
