# Generated by Django 3.2.4 on 2022-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productflower_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_without_allowance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
