# Generated by Django 3.2.4 on 2022-03-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220319_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('На продаже', 'На продаже'), ('Продан', 'Продан'), ('В процессе доставки', 'В процессе доставки'), ('Удален', 'Удален')], default='На продаже', max_length=255),
        ),
    ]
