# Generated by Django 3.2.4 on 2022-03-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='working_schedule',
            field=models.CharField(blank=True, choices=[('Дневной', 'Дневной'), ('Вечерний', 'Вечерний')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('florist', 'Флорист'), ('courier', 'Курьер'), ('admin', 'Админ')], default='client', max_length=255, null=True),
        ),
    ]
