# Generated by Django 3.2.4 on 2022-03-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='shop_branch',
        ),
        migrations.AddField(
            model_name='user',
            name='shop_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.shopbranch'),
        ),
    ]
