# Generated by Django 3.2.4 on 2022-04-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220325_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopbranch',
            old_name='latitude',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='shopbranch',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.shopbranch'),
        ),
    ]
