# Generated by Django 3.2.4 on 2022-04-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220414_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shopbranch'),
        ),
    ]
