# Generated by Django 3.2.4 on 2022-03-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255, null=True)),
                ('sender_phone_number', models.CharField(max_length=255, null=True)),
                ('receiver_name', models.CharField(max_length=255, null=True)),
                ('receiver_phone_number', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('postcard_text', models.TextField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('money_change_status', models.BooleanField(default=False)),
                ('client_money_value', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('received_date', models.DateField()),
                ('received_time', models.TimeField()),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('В ожидании курьера', 'В ожидании курьера'), ('Курьер принял заказ', 'Курьер принял заказ'), ('Курьер едет к нам', 'Курьер едет к нам'), ('Заказ у курьера', 'Заказ у курьера'), ('Ваш заказ в пути', 'Ваш заказ в пути'), ('Доставлено', 'Доставлено'), ('Отменен', 'Отменен')], max_length=255)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
            ],
        ),
    ]
