# Generated by Django 3.2.4 on 2022-03-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productflower_product'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(limit_choices_to={'status': 'На продаже'}, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(limit_choices_to={'is_ordered': False}, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
    ]
